# TASK #1: DEFINE SINGLE AND MULTI-DIMENSIONAL  NUMPY ARRAYS

In [12]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 

import numpy as np

# Let's define a one-dimensional array 

list_onedim=[1,2,3,4,5,6,7,8,9]
list_onedim

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
# Let's create a numpy array from the list "my_list"
onedim_array=np.array(list_onedim)
onedim_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
type(onedim_array)

numpy.ndarray

In [15]:
# Multi-dimensional (Matrix definition) 
matrix=np.array([[1,2,3],[5,7,8],[4,8,6]])
matrix

array([[1, 2, 3],
       [5, 7, 8],
       [4, 8, 6]])

MINI CHALLENGE #1: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [16]:
MC1=np.array([[3,7,9,3],[4,3,2,2]])
MC1

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

# TASK #2: LEVERAGE NUMPY BUILT-IN METHODS AND FUNCTIONS 

In [17]:
# "rand()" uniform distribution between 0 and 1
rand=np.random.rand(20)
rand

array([0.72325757, 0.63482456, 0.18053859, 0.8625601 , 0.94844854,
       0.50911053, 0.25424263, 0.49670803, 0.84697784, 0.07156051,
       0.33513399, 0.57378075, 0.18971776, 0.70557853, 0.81329504,
       0.55501277, 0.4880623 , 0.20823381, 0.52920506, 0.64929481])

In [18]:
# you can create a matrix of random number as well
rmatrix=np.random.rand(2,2)
rmatrix

array([[0.30912351, 0.70465283],
       [0.10534656, 0.10159385]])

In [19]:
# "randint" is used to generate random integers between upper and lower bounds
x=np.random.randint(1,20)
x

8

In [20]:
# "randint" can be used to generate a certain number of random itegers as follows
x=np.random.randint(1,10,5)
x

array([7, 9, 8, 2, 9])

In [21]:
# np.arange creates an evenly spaced values within a given interval
x=np.arange(1,21)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [22]:
# create a diagonal of ones and zeros everywhere else
x=np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
# Matrix of ones
x=np.ones((2,2))
x

array([[1., 1.],
       [1., 1.]])

In [24]:
# Array of zeros
x=np.zeros((2,3))
x

array([[0., 0., 0.],
       [0., 0., 0.]])

MINI CHALLENGE #2:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [25]:
x=input('Enter a positive integer: ')
MC2=np.random.randint(1,x,10)
MC2

Enter a positive integer: 10


array([2, 7, 6, 5, 2, 3, 1, 6, 9, 8])

# TASK #3: PERFORM MATHEMATICAL OPERATIONS IN NUMPY

In [26]:
# np.arange() returns an evenly spaced values within a given interval
x=np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
y=np.arange(11,21)
y

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [28]:
# Add 2 numpy arrays together
sum=x+y
sum

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [29]:
xsqu=x**2
xsqu

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [30]:
sqrt=np.sqrt(xsqu)
sqrt

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [31]:
z=np.exp(y)
z

array([5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
       3.26901737e+06, 8.88611052e+06, 2.41549528e+07, 6.56599691e+07,
       1.78482301e+08, 4.85165195e+08])

MINI CHALLENGE #3:
- Given the X and Y values below, obtain the distance between them

```
X = [5, 7, 20]
Y = [9, 15, 4]
```

In [32]:
x=np.array([5,7,20])
y=np.array([9,15,4])
dist=np.sqrt(np.sum((x-y)**2)) 
dist

18.33030277982336

# TASK #4: PERFORM ARRAYS SLICING AND INDEXING 

In [33]:
m_arr=np.array([1,2,3,4,5,6,7,8,9,50])
m_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 50])

In [34]:
# Access specific index from the numpy array
m_arr[-1]

50

In [35]:
# Starting from the first index 0 up until and NOT including the last element
m_arr[1:3]

array([2, 3])

In [36]:
# Broadcasting, altering several values in a numpy array at once
m_arr[0:3]=0
m_arr

array([ 0,  0,  0,  4,  5,  6,  7,  8,  9, 50])

In [37]:
# Let's define a two dimensional numpy array
m_mtx=np.random.randint(1,10,(3,3))
m_mtx

array([[2, 2, 1],
       [3, 5, 1],
       [2, 3, 3]])

In [38]:
# Get a row from a mtrix
m_mtx[0]

array([2, 2, 1])

In [39]:
# Get one element
m_mtx[0][1]

2

MINI CHALLENGE #4:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [40]:
x=np.array([[2,30,20,-2,-4],[3,4,40,-3,-2],[-3,4,-6,90,10],[25,45,34,22,12],[13,24,22,32,37]])
x[-1]=0
x

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

# TASK #5: PERFORM ELEMENTS SELECTION (CONDITIONAL)

In [41]:
m_mtx=np.random.randint(1,10,(5,5))
m_mtx

array([[7, 7, 8, 2, 2],
       [5, 5, 5, 8, 8],
       [3, 1, 6, 3, 5],
       [6, 3, 7, 9, 1],
       [5, 2, 5, 1, 9]])

In [42]:
n_mtx=m_mtx[m_mtx>8]
n_mtx

array([9, 9])

In [43]:
# Obtain odd elements only
n_mtx=m_mtx[m_mtx%2 == 1]
n_mtx

array([7, 7, 5, 5, 5, 3, 1, 3, 5, 3, 7, 9, 1, 5, 5, 1, 9])

MINI CHALLENGE #5:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [44]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12], 
    [13, 24, 22, 32, 37]])
X


array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [45]:
X[X<0]=0
X[X%2 == 1]=-2
X

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

# TASK #6: UNDERSTAND PANDAS FUNDAMENTALS

In [46]:
# Pandas is a data manipulation and analysis tool that is built on Numpy.
# Pandas uses a data structure known as DataFrame (think of it as Microsoft excel in Python). 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows and columns).
# Series Vs. DataFrame? Series is considered a single column of a DataFrame.

In [47]:
import pandas as pd

In [48]:
# Let's define a two-dimensional Pandas DataFrame
# Note that you can create a pandas dataframe from a python dictionary
bank_df =pd.DataFrame({'Bank Client Id':[123,223,323,423],
                      'Bank Client Name':['Chanell','Hermes','LV','Chloe'],
                      'Net Worth [$]':[2020,20000,4389,10000],
                      'Yearth with bank':[3,4,8,3]}) 
bank_df

Bank Client Id Bank Client Name  Net Worth [$]  Yearth with bank
0             123          Chanell           2020                 3
1             223           Hermes          20000                 4
2             323               LV           4389                 8
3             423            Chloe          10000                 3

In [49]:
# Let's obtain the data type 
type(bank_df)

pandas.core.frame.DataFrame

In [50]:
# you can only view the first couple of rows using .head()
bank_df.head(1)

Bank Client Id Bank Client Name  Net Worth [$]  Yearth with bank
0             123          Chanell           2020                 3

In [51]:
# you can only view the last couple of rows using .tail()
bank_df.tail(3)

Bank Client Id Bank Client Name  Net Worth [$]  Yearth with bank
1             223           Hermes          20000                 4
2             323               LV           4389                 8
3             423            Chloe          10000                 3

MINI CHALLENGE #6:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [52]:
portfolio_df =pd.DataFrame({'Ticker':['AMZN','GM','GOOG'],
                      'Number of shares':[46,10,13],
                      'Price per share[$]':[915,33,878]}) 
portfolio_df

Ticker  Number of shares  Price per share[$]
0   AMZN                46                 915
1     GM                10                  33
2   GOOG                13                 878

In [53]:
tot_val=np.sum(portfolio_df['Price per share[$]']*portfolio_df['Number of shares'])
tot_val

53834

# TASK #7: PANDAS WITH CSV AND HTML DATA

In [54]:
!python -m pip install --upgrade pip
!pip install lxml

/bin/bash: python: command not found


In [55]:
# Read tabular data using read_html
house_price_df = pd.read_html('https://www.livingin-canada.com/house-prices-canada.html')

In [56]:
house_price_df[0]

City  \
0                                      Vancouver, BC   
1                                       Toronto, Ont   
2                                        Ottawa, Ont   
3                                       Calgary, Alb   
4                                      Montreal, Que   
5                                        Halifax, NS   
6                                       Regina, Sask   
7                                    Fredericton, NB   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                 Average House Price  \
0                                         $1,036,000   
1                                           $870,000   
2                                           $479,000   
3                                           $410,000   
4                                           $435,000   
5                                           $331,000   
6                                           $254,000   
7                                           $198,000   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                     12 Month Change  
0                                           + 2.63 %  
1                                            +10.2 %  
2                                           + 15.4 %  
3                                            – 1.5 %  
4                                            + 9.3 %  
5                                            + 3.6 %  
6                                            – 3.9 %  
7                                            – 4.3 %  
8  (adsbygoogle = window.adsbygoogle || []).push(...

In [57]:
house_price_df[1]

Province  \
0                                    British Columbia   
1                                             Ontario   
2                                             Alberta   
3                                              Quebec   
4                                            Manitoba   
5                                        Saskatchewan   
6                                         Nova Scotia   
7                                Prince Edward Island   
8                             Newfoundland / Labrador   
9                                       New Brunswick   
10                                   Canadian Average   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                  Average House Price  \
0                                            $736,000   
1                                            $594,000   
2                                            $353,000   
3                                            $340,000   
4                                            $295,000   
5                                            $271,000   
6                                            $266,000   
7                                            $243,000   
8                                            $236,000   
9                                            $183,000   
10                                           $488,000   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                      12 Month Change  
0                                             + 7.6 %  
1                                             – 3.2 %  
2                                             – 7.5 %  
3                                             + 7.6 %  
4                                             – 1.4 %  
5                                             – 3.8 %  
6                                             + 3.5 %  
7                                             + 3.0 %  
8                                             – 1.6 %  
9                                             – 2.2 %  
10                                            – 1.3 %  
11  (adsbygoogle = window.adsbygoogle || []).push(...

MINI CHALLENGE #7:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [58]:
retirement_df=pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
retirement_df[0]

Year of birth  \
0                                      1937 and prior   
1                                                1938   
2                                                1939   
3                                                1940   
4                                                1941   
5                                                1942   
6                                             1943-54   
7                                                1955   
8                                                1956   
9                                                1957   
10                                               1958   
11                                               1959   
12                                     1960 and later   
13  Notes: 1. Persons born on January 1 of any yea...   

                                                  Age  
0                                                  65  
1                                     65 and 2 months  
2                                     65 and 4 months  
3                                     65 and 6 months  
4                                     65 and 8 months  
5                                    65 and 10 months  
6                                                  66  
7                                     66 and 2 months  
8                                     66 and 4 months  
9                                     66 and 6 months  
10                                    66 and 8 months  
11                                   66 and 10 months  
12                                                 67  
13  Notes: 1. Persons born on January 1 of any yea...

# TASK #8: PANDAS OPERATIONS

In [59]:
# Let's define a dataframe as follows:
bank_df.head()

Bank Client Id Bank Client Name  Net Worth [$]  Yearth with bank
0             123          Chanell           2020                 3
1             223           Hermes          20000                 4
2             323               LV           4389                 8
3             423            Chloe          10000                 3

In [60]:
# Pick certain rows that satisfy a certain criteria 
loyal_df = bank_df[bank_df["Yearth with bank"]>=4]
loyal_df

Bank Client Id Bank Client Name  Net Worth [$]  Yearth with bank
1             223           Hermes          20000                 4
2             323               LV           4389                 8

In [61]:
# Delete a column from a DataFrame
del loyal_df['Net Worth [$]']
loyal_df

Bank Client Id Bank Client Name  Yearth with bank
1             223           Hermes                 4
2             323               LV                 8

MINI CHALLENGE #8:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [62]:
reach_df=bank_df[bank_df['Net Worth [$]']>=5000]
reach_df

Bank Client Id Bank Client Name  Net Worth [$]  Yearth with bank
1             223           Hermes          20000                 4
3             423            Chloe          10000                 3

In [63]:
total_worth=np.sum(reach_df['Net Worth [$]'])
total_worth

30000

# TASK #9: PANDAS WITH FUNCTIONS

In [64]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [65]:
# Define a function that increases all clients networth (stocks) by a fixed value of 20% (for simplicity sake) 

def worth_inc(balance):
    return balance*1.2

In [66]:
# You can apply a function to the DataFrame 
bank_client_df['Net worth [$]'].apply(worth_inc)

0     4200.0
1    34800.0
2    12000.0
3     2400.0
Name: Net worth [$], dtype: float64

In [67]:
bank_client_df['Bank Client Name'].apply(len)

0    6
1    5
2    5
3    4
Name: Bank Client Name, dtype: int64

MINI CHALLENGE #9:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [68]:
def tripplestock(value):
    return value*3+200

In [69]:
portfolio_df['Price per share[$]'].apply(tripplestock)

0    2945
1     299
2    2834
Name: Price per share[$], dtype: int64

In [70]:
portfolio_df['Price per share[$]'].apply(tripplestock).sum()

6078

# TASK #10: PERFORM SORTING AND ORDERING IN PANDAS

In [71]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [72]:
# You can sort the values in the dataframe according to number of years with bank
bank_client_df.sort_values(by = 'Years with bank')

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

In [73]:
# Note that nothing changed in memory! you have to make sure that inplace is set to True
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [74]:
# Set inplace = True to ensure that change has taken place in memory 
bank_client_df.sort_values(by='Years with bank', inplace=True)

In [75]:
# Note that now the change (ordering) took place 
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

# TASK #11: PERFORM CONCATENATING AND MERGING WITH PANDAS

In [76]:
# Check this out: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

In [77]:
df1=pd. DataFrame({'A':['A0','A1','A2', 'A3'],
                   'B':['B0','B1','B2', 'B3'],
                   'C':['C0','C1','C2', 'C3'],
                   'D':['D0','D1','D2', 'D3']},
                   index=[0,1,2,3]
                  )
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [78]:
df1.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [79]:
df2=pd. DataFrame({'A':['A4','A5','A6', 'A7'],
                   'B':['B4','B5','B6', 'B7'],
                   'C':['C4','C5','C6', 'C7'],
                   'D':['D4','D5','D6', 'D7']},
                   index=[4,5,6,7]
                  )
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [80]:
df3=pd. DataFrame({'A':['A8','A9','A10', 'A11'],
                   'B':['B8','B9','B10', 'B11'],
                   'C':['C8','C9','C10', 'C11'],
                   'D':['D8','D9','D10', 'D11']},
                   index=[8,9,10,11]
                  )
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [81]:
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

# TASK #12: PROJECT AND CONCLUDING REMARKS

- Define a dataframe named 'Bank_df_1' that contains the first and last names for 5 bank clients with IDs = 1, 2, 3, 4, 5 
- Assume that the bank got 5 new clients, define another dataframe named 'Bank_df_2' that contains a new clients with IDs = 6, 7, 8, 9, 10
- Let's assume we obtained additional information (Annual Salary) about all our bank customers (10 customers) 
- Concatenate both 'bank_df_1' and 'bank_df_2' dataframes
- Merge client names and their newly added salary information using the 'Bank Client ID'
- Let's assume that you became a new client to the bank
- Define a new DataFrame that contains your information such as client ID (choose 11), first name, last name, and annual salary.
- Add this new dataframe to the original dataframe 'bank_df_all'.

In [82]:
bank_df_1=pd.DataFrame({'ID':[1,2,3,4,5],
                        'First Name':['Nick','Amy','Diana','Rose','Pit'],
                        'Last Name':['Candy','Grgson','Black','Jhonson','Fudgy']
                       },
                      index=[1,2,3,4,5])
bank_df_2=pd.DataFrame({'ID':[6,7,8,9,10],
                        'First Name':['Antony','Noel','Hanna','Hesus','Kim'],
                        'Last Name':['Richards','Green','Smith','Savier','Pohlun']
                       },
                      index=[6,7,8,9,10])

In [83]:
bank_full=pd.concat([bank_df_1, bank_df_2])
bank_full

ID First Name Last Name
1    1       Nick     Candy
2    2        Amy    Grgson
3    3      Diana     Black
4    4       Rose   Jhonson
5    5        Pit     Fudgy
6    6     Antony  Richards
7    7       Noel     Green
8    8      Hanna     Smith
9    9      Hesus    Savier
10  10        Kim    Pohlun

In [84]:
salary_df=pd.DataFrame({'ID':[1,2,3,4,5,6,7,8,9,10],
                        'Annual Salary':[1000,3000,2347,12837,66347,6847,787,8345,92374,1838]
                       })

In [85]:
bank_full=pd.merge(bank_full,salary_df,on='ID')
bank_full

ID First Name Last Name  Annual Salary
0   1       Nick     Candy           1000
1   2        Amy    Grgson           3000
2   3      Diana     Black           2347
3   4       Rose   Jhonson          12837
4   5        Pit     Fudgy          66347
5   6     Antony  Richards           6847
6   7       Noel     Green            787
7   8      Hanna     Smith           8345
8   9      Hesus    Savier          92374
9  10        Kim    Pohlun           1838

In [86]:
bank_df_3=pd.DataFrame({'ID':[11],
                        'First Name':['Emily'],
                        'Last Name':['Coldflow'],
                        'Annual Salary':[11700]
                       })
bank_df_3

ID First Name Last Name  Annual Salary
0  11      Emily  Coldflow          11700

In [87]:
bank_full=pd.concat([bank_full,bank_df_3], ignore_index= True)
bank_full

ID First Name Last Name  Annual Salary
0    1       Nick     Candy           1000
1    2        Amy    Grgson           3000
2    3      Diana     Black           2347
3    4       Rose   Jhonson          12837
4    5        Pit     Fudgy          66347
5    6     Antony  Richards           6847
6    7       Noel     Green            787
7    8      Hanna     Smith           8345
8    9      Hesus    Savier          92374
9   10        Kim    Pohlun           1838
10  11      Emily  Coldflow          11700